Resources:
  LoggerHandlerServiceRole485E0CBB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: AuditLoggerStack/LoggerHandler/ServiceRole/Resource
  LoggerHandler842BC60D:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters8b51a0d2d419180003d634c2551aeaaf80cb356e5fb8d787a6ea5bf982ee3f25S3BucketB81B0BFD
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters8b51a0d2d419180003d634c2551aeaaf80cb356e5fb8d787a6ea5bf982ee3f25S3VersionKeyBD37BE5E
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters8b51a0d2d419180003d634c2551aeaaf80cb356e5fb8d787a6ea5bf982ee3f25S3VersionKeyBD37BE5E
      Handler: logger.handler
      Role:
        Fn::GetAtt:
          - LoggerHandlerServiceRole485E0CBB
          - Arn
      Runtime: nodejs12.x
    DependsOn:
      - LoggerHandlerServiceRole485E0CBB
    Metadata:
      aws:cdk:path: AuditLoggerStack/LoggerHandler/Resource
      aws:asset:path: /home/brian/sandbox/audit-logger-lambda/AuditLogger/lambda
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.67.0,@aws-cdk/assets=1.67.0,@aws-cdk/aws-applicationautoscaling=1.67.0,@aws-cdk/aws-autoscaling-common=1.67.0,@aws-cdk/aws-cloudwatch=1.67.0,@aws-cdk/aws-codeguruprofiler=1.67.0,@aws-cdk/aws-ec2=1.67.0,@aws-cdk/aws-events=1.67.0,@aws-cdk/aws-iam=1.67.0,@aws-cdk/aws-kms=1.67.0,@aws-cdk/aws-lambda=1.67.0,@aws-cdk/aws-logs=1.67.0,@aws-cdk/aws-s3=1.67.0,@aws-cdk/aws-s3-assets=1.67.0,@aws-cdk/aws-sqs=1.67.0,@aws-cdk/aws-ssm=1.67.0,@aws-cdk/cloud-assembly-schema=1.67.0,@aws-cdk/core=1.67.0,@aws-cdk/cx-api=1.67.0,@aws-cdk/region-info=1.67.0,jsii-runtime=node.js/v12.15.0
    Metadata:
      aws:cdk:path: AuditLoggerStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters8b51a0d2d419180003d634c2551aeaaf80cb356e5fb8d787a6ea5bf982ee3f25S3BucketB81B0BFD:
    Type: String
    Description: S3 bucket for asset "8b51a0d2d419180003d634c2551aeaaf80cb356e5fb8d787a6ea5bf982ee3f25"
  AssetParameters8b51a0d2d419180003d634c2551aeaaf80cb356e5fb8d787a6ea5bf982ee3f25S3VersionKeyBD37BE5E:
    Type: String
    Description: S3 key for asset version "8b51a0d2d419180003d634c2551aeaaf80cb356e5fb8d787a6ea5bf982ee3f25"
  AssetParameters8b51a0d2d419180003d634c2551aeaaf80cb356e5fb8d787a6ea5bf982ee3f25ArtifactHashC2659A29:
    Type: String
    Description: Artifact hash for asset "8b51a0d2d419180003d634c2551aeaaf80cb356e5fb8d787a6ea5bf982ee3f25"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

